---
- hosts: db1
  sudo: yes

  pre_tasks:
    - name: reconfigure locales
      shell: dpkg-reconfigure locales

  roles:
    - postgresql

  tasks:
    - name: Add authorized postgres's key for marcos-summa
      action: authorized_key user=postgres key="{{ lookup('file', 'marcos.pub') }}"

    - name: Add authorized postgres's key for marcos-mac
      action: authorized_key user=postgres key="{{ lookup('file', 'marcos-mac.pub') }}"

    - name: Add postgres user to sudoers
      action: lineinfile dest=/etc/sudoers regexp="postgres ALL" line="postgres ALL=(ALL) NOPASSWD:ALL" state=present



    - name: restart postgresql
      sudo: yes
      service: name=postgresql state=restarted

######## configuring Postgres
#- hosts: db1
#  sudo: yes
#  sudo_user: postgres
#  gather_facts: no

#  tasks:
#    - name: postgresql should listen on all ports
#      lineinfile: dest=/etc/postgresql/9.4/main/postgresql.conf
#                  regexp="^listen_addresses"
#                  line="listen_addresses = '*'" state=present

#    - name: postgresql should allow access to host
#      copy:
#        dest: /etc/postgresql/9.4/main/pg_hba.conf
#        content: |
#          local   all   postgres   peer
#          local   all   all        peer
#          host    all   all        0.0.0.0/0   md5

#    - name: restart postgresql
#      sudo: yes
#      service: name=postgresql state=restarted
